### ISSUE TITLE
users-can-log-in-to-a-room

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#1]
## 💰 Motivation

User will want to join a room to play the game.

## 📐 Plan

Create a form where users will submit a room code and name.

That user will then either create a room or join a room.

## 🖼️ Wireframe

![user can view the temporary room joining page]
![image](https://user-images.githubusercontent.com/6721652/106645832-c0fcba80-6541-11eb-8916-fb3b5f639862.png)

## ✅ Task List

- [x] Create a HTML skeleton
- [x] Create header component
- [x] Create a form component
- [x] Create a chat room component
- [x] Create handshake between server and client
- [x] Add CSS styling
- [x] Test features
- [x] Fix bugs
- [x] Test again
