### ISSUE TITLE
users-can-begin-matching-phase

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#10]
## 💰 Motivation

User will want to begin matching phase of the game. Users will be sent the final list of restaurants and begin liking or disliking the choices.

## 📐 Plan

Create logic to send a message to the server that will indicate the list is finalized. The server will then begin the game and send yelp items to the users.

## ✅ Task List

- [x] Create logic on the client to send a message to the server
- [x] Create server logic to send the client the finalized array
- [x] Test features
- [x] Fix bugs
- [x] Test features again
