### ISSUE TITLE
users-can-see-a-match

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#11]
## 💰 Motivation

User will want to know when a match is made

## 📐 Plan

Create logic to indicate a match has been found

## ✅ Task List

- [ ] Create server logic to indicate when a place has likes from all users or the list is exhausted, if it is exhausted then take the one with the most likes, if there is a tie then choose at random
- [ ] Send the matched yelp item back to the users
- [ ] Test features
- [ ] Fix bugs
- [ ] Test features again
