### ISSUE TITLE
users-can-chat

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#2]
## 💰 Motivation

Users will want to communicate with each other

## 📐 Plan

Create the events to send messages and place them on the view

## 🖼️ Wireframe

![user can chat]
![image](https://user-images.githubusercontent.com/6721652/106646779-f35ae780-6542-11eb-9a99-8b4246697c01.png)

## ✅ Task List

- [x] Create a chat bar in the chat room component
- [x] Create message listeners on the server
- [x] Create message events on the client
- [x] Create the functions to place messages on the front end
- [x] Test functionality
- [x] Fix bugs
- [x] Test again
