### ISSUE TITLE
users-can-see-lobby

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#3]
## 💰 Motivation

User will want to view who is in the lobby
## 📐 Plan

Create a component that stores the users connected to the room

## 🖼️ Wireframe

![user can view whos in the lobby]
![image](https://user-images.githubusercontent.com/6721652/106647005-3ae17380-6543-11eb-833a-da9611103719.png)

## ✅ Task List

- [x] Modify the room joining message function to add users to an array
- [x] Modify the room leaving message and remove user from array
- [x] Create a list to display on the front end
- [ ] OPTIONAL: Make into an app drawer
- [x] Test functionality
- [x] Fix bugs
- [x] Test functionality
