### ISSUE TITLE
users-can-search-yelp-api

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#4]
## 💰 Motivation

Users will need to search yelp API for restaurants 

## 📐 Plan

Create a view where the user can search through yelp

## 🖼️ Wireframe

![user can view the search page]
![image](https://user-images.githubusercontent.com/6721652/106647444-cbb84f00-6543-11eb-8ef0-372f35c9e187.png)

## ✅ Task List

- [x] Create a HTML skeleton
- [x] Create a search page component
- [x] Add search button
- [x] Add location button
- [x] Create backend to retrieve data from Yelp API
- [x] Add CSS
- [x] Test Functionality
- [x] Test for bugs
- [x] Test functionality again
