### ISSUE TITLE
users-can-view-search-list

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#5]
## 💰 Motivation

User will want to view places found by their yelp search

## 📐 Plan

Create a view where the user can see a list of restaurants 

## 🖼️ Wireframe

![user can view the search page]
![image](https://user-images.githubusercontent.com/6721652/106648009-847e8e00-6544-11eb-8141-1d7090c7c072.png)

## ✅ Task List

- [x] Create a HTML skeleton
- [x] Create a box list component for yelp results
- [x] Map search data to front end
- [x] Create buttons to add restaurant to the array
- [x] Create a next page button to store other results
- [x] Test functionality
- [x] Fix bugs
- [x] Test functionality again
