### ISSUE TITLE
users-can-get-more-information-on-yelp-page

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#6]
## 💰 Motivation

User will want to view more information regarding restaurants

## 📐 Plan

Create a button that will redirect the user to the yelp page in a new tab

## 🖼️ Wireframe

![user can view the yelp page]
![image](https://user-images.githubusercontent.com/6721652/106648538-45047180-6545-11eb-9447-131e110daaf9.png)

## ✅ Task List

- [x] Add a button the list item
- [x] Create functionality to redirect user to the yelp page
- [x] Test features
- [x] Fix bugs
- [x] Test features again
