### ISSUE TITLE
users-can-see-yelp-pages-from-other-users

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#7]
## 💰 Motivation

User will want to view restaurant choices from other users

## 📐 Plan

Create a view where the user can see choices from users and decide like or dislike

## 🖼️ Wireframe

![user can view the homepage]
![image](https://user-images.githubusercontent.com/6721652/106648891-bba16f00-6545-11eb-9df8-32ce24a79bb6.png)

## ✅ Task List

- [x] Create a HTML skeleton
- [x] Create a card component to display yelp information
- [x] Create a button for like
- [x] Create a button for dislike
- [x] Create a button to redirect yelp page
- [x] Test functionality
- [x] Fix bugs
- [x] Test again
