### ISSUE TITLE
users-can-like-other-user-choices

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#8]
## 💰 Motivation

User will want to like or dislike other user choices

## 📐 Plan

Create logic to add the yelp item to an array and pass it to the server

## ✅ Task List

- [x] Create functionality to like clicks
- [x] Create handshake for server to add the yelp item to the liked list
- [x] Test features
- [x] Fix bugs
- [ ] Test features again
