### ISSUE TITLE
user-can-start-search-phase

### ISSUE THREAD

**Issue by michaelvalenzuela** [michaelvalenzuela/tender#9]
## 💰 Motivation

Host of the lobby will want to start the game to begin the search phase

## 📐 Plan

Create a button in the chat room lobby to allow the host to begin the game.

The game will be played for varying amounts of 5, 10, 15, 20 minutes.

## ✅ Task List

- [x] Add a button to the chat room for the host
- [x] Create logic to ask the host how long to play
- [x] Test features
- [x] Fix bugs
- [x] Test features again
